# Generated by Django 5.1 on 2024-09-01 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS50_News', '0002_alter_new_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='auther',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publishes', to=settings.AUTH_USER_MODEL),
        ),
    ]
