# Generated by Django 5.1 on 2024-09-21 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS50_News', '0005_alter_new_auther_alter_new_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='validation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='auther',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publishes', to=settings.AUTH_USER_MODEL),
        ),
    ]
