# Generated by Django 5.1 on 2024-09-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS50_News', '0006_user_validation_date_alter_new_auther'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
