# Generated by Django 5.1 on 2024-11-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS50_News', '0007_user_otp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='category',
            field=models.CharField(choices=[('M', 'main'), ('N', 'news'), ('US', 'us_elections'), ('S', 'sport'), ('B', 'business'), ('I', 'innovation'), ('C', 'culture'), ('A', 'art'), ('T', 'travel'), ('E', 'earth')], max_length=50),
        ),
        migrations.AlterField(
            model_name='new',
            name='sub_category',
            field=models.CharField(blank=True, default=models.CharField(choices=[('M', 'main'), ('N', 'news'), ('US', 'us_elections'), ('S', 'sport'), ('B', 'business'), ('I', 'innovation'), ('C', 'culture'), ('A', 'art'), ('T', 'travel'), ('E', 'earth')], max_length=50), max_length=50, null=True),
        ),
    ]
