# Generated by Django 5.1 on 2024-11-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS50_News', '0008_alter_new_category_alter_new_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='content',
            field=models.TextField(max_length=10000),
        ),
    ]
