# Generated by Django 5.1 on 2024-11-09 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS50_News', '0009_alter_new_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('N', 'News'), ('IG', 'Israil-Gaza_war'), ('UR', 'Ukraine-Russia_war'), ('IQ', 'Iraq'), ('US&C', 'US_&_Canada'), ('MD', 'Middle_East'), ('EU', 'Europe'), ('AS', 'Asia'), ('AF', 'Africa'), ('AU', 'Australia'), ('LA', 'Latine_America'), ('SP', 'Sport'), ('MA', 'Martial_Arts'), ('FB', 'Football'), ('IN', 'Innovation'), ('TECH', 'Technology'), ('HE', 'Health'), ('CU', 'Culture'), ('BOOK', 'Books'), ('STY', 'Style'), ('', '')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='new',
            name='category',
            field=models.CharField(choices=[('N', 'News'), ('S', 'Sport'), ('B', 'Business'), ('I', 'Innovation'), ('C', 'Culture'), ('A', 'Art'), ('T', 'Travel'), ('E', 'Earth')], max_length=50),
        ),
        migrations.AlterField(
            model_name='new',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CS50_News.sub_category'),
        ),
    ]
