# Generated by Django 5.1 on 2024-11-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS50_News', '0010_sub_category_alter_new_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='new',
            name='sub_category',
            field=models.ManyToManyField(to='CS50_News.sub_category'),
        ),
    ]
