# Generated by Django 5.1 on 2024-11-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS50_News', '0011_remove_new_sub_category_new_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='scroll',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='new',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
