# Generated by Django 5.1 on 2024-11-14 16:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS50_News', '0012_new_scroll_new_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
