# Generated by Django 5.1 on 2024-11-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS50_News', '0013_new_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='sub_category',
        ),
        migrations.DeleteModel(
            name='Sub_Category',
        ),
        migrations.AddField(
            model_name='new',
            name='sub_category',
            field=models.CharField(choices=[('N', 'News'), ('IG', 'Israil-Gaza_war'), ('UR', 'Ukraine-Russia_war'), ('IQ', 'Iraq'), ('US&C', 'US_&_Canada'), ('MD', 'Middle_East'), ('EU', 'Europe'), ('AS', 'Asia'), ('AF', 'Africa'), ('AU', 'Australia'), ('LA', 'Latine_America'), ('SP', 'Sport'), ('MA', 'Martial_Arts'), ('FB', 'Football'), ('IN', 'Innovation'), ('TECH', 'Technology'), ('HE', 'Health'), ('CU', 'Culture'), ('BOOK', 'Books'), ('STY', 'Style'), ('', '')], default='IG', max_length=25),
        ),
    ]
