# Generated by Django 5.1.3 on 2024-11-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS50_News', '0014_remove_new_sub_category_delete_sub_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='score',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='new',
            name='sub_category',
            field=models.CharField(choices=[('N', 'News'), ('IG', 'Israil-Gaza war'), ('UR', 'Ukraine-Russia war'), ('IQ', 'Iraq'), ('US&C', 'US & Canada'), ('MD', 'Middle East'), ('EU', 'Europe'), ('AS', 'Asia'), ('AF', 'Africa'), ('AU', 'Australia'), ('LA', 'Latine America'), ('SP', 'Sport'), ('MA', 'Martial Arts'), ('FB', 'Football'), ('IN', 'Innovation'), ('TECH', 'Technology'), ('HE', 'Health'), ('CU', 'Culture'), ('BOOK', 'Books'), ('STY', 'Style'), ('', '')], default='IG', max_length=25),
        ),
    ]
