# Generated by Django 5.1.3 on 2024-11-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS50_News', '0015_new_score_alter_new_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='category',
        ),
        migrations.RemoveField(
            model_name='new',
            name='sub_category',
        ),
        migrations.AlterField(
            model_name='new',
            name='content',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('N', 'News'), ('S', 'Sport'), ('B', 'Business'), ('I', 'Innovation'), ('C', 'Culture'), ('A', 'Art'), ('T', 'Travel'), ('E', 'Earth'), ('IG', 'Israil-Gaza war'), ('UR', 'Ukraine-Russia war'), ('IQ', 'Iraq'), ('US&C', 'US & Canada'), ('MD', 'Middle East'), ('EU', 'Europe'), ('AS', 'Asia'), ('AF', 'Africa'), ('AU', 'Australia'), ('LA', 'Latine America'), ('MA', 'Martial Arts'), ('FB', 'Football'), ('TECH', 'Technology'), ('HE', 'Health'), ('BOOK', 'Books'), ('STY', 'Style')], max_length=50)),
                ('parent', models.CharField(blank=True, choices=[('N', 'News'), ('S', 'Sport'), ('B', 'Business'), ('I', 'Innovation'), ('C', 'Culture'), ('A', 'Art'), ('T', 'Travel'), ('E', 'Earth'), ('IG', 'Israil-Gaza war'), ('UR', 'Ukraine-Russia war'), ('IQ', 'Iraq'), ('US&C', 'US & Canada'), ('MD', 'Middle East'), ('EU', 'Europe'), ('AS', 'Asia'), ('AF', 'Africa'), ('AU', 'Australia'), ('LA', 'Latine America'), ('MA', 'Martial Arts'), ('FB', 'Football'), ('TECH', 'Technology'), ('HE', 'Health'), ('BOOK', 'Books'), ('STY', 'Style')], max_length=50, null=True)),
                ('news', models.ManyToManyField(related_name='category', to='CS50_News.new')),
            ],
        ),
    ]
