# Generated by Django 5.1.3 on 2024-11-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS50_News', '0016_remove_new_category_remove_new_sub_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='news',
            field=models.ManyToManyField(blank=True, null=True, related_name='category', to='CS50_News.new'),
        ),
    ]
