# Generated by Django 5.1.3 on 2024-12-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS50_News', '0017_alter_category_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='scroll',
        ),
        migrations.AddField(
            model_name='new',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('N', 'News'), ('S', 'Sport'), ('B', 'Business'), ('I', 'Innovation'), ('C', 'Culture'), ('T', 'Travel'), ('E', 'Earth'), ('IG', 'Israil-Gaza_war'), ('UR', 'Ukraine-Russia_war'), ('IQ', 'Iraq'), ('US&C', 'US_&_Canada'), ('MD', 'Middle_East'), ('EU', 'Europe'), ('AS', 'Asia'), ('AF', 'Africa'), ('AU', 'Australia'), ('LA', 'Latine_America'), ('MA', 'Martial_Arts'), ('FB', 'Football'), ('CR', 'Cricket'), ('F1', 'Formula_1'), ('TE', 'Tennis'), ('GO', 'Golf'), ('AT', 'Athletics'), ('CY', 'Cycling'), ('TECH', 'Technology'), ('S&HE', 'Science_&_Health'), ('BOOK', 'Books'), ('ST', 'Style'), ('TV', 'Film_&_TV'), ('MS', 'Music'), ('AR&D', 'Art_&_Design'), ('EN', 'Entertainment'), ('DE', 'Destinations'), ('FOOD', 'Food_&_Drink'), ('AD', 'Adventures'), ('NW', 'Natural_Wonders'), ('WE&C', 'Weather_&_Climate')], max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.CharField(blank=True, choices=[('N', 'News'), ('S', 'Sport'), ('B', 'Business'), ('I', 'Innovation'), ('C', 'Culture'), ('T', 'Travel'), ('E', 'Earth'), ('IG', 'Israil-Gaza_war'), ('UR', 'Ukraine-Russia_war'), ('IQ', 'Iraq'), ('US&C', 'US_&_Canada'), ('MD', 'Middle_East'), ('EU', 'Europe'), ('AS', 'Asia'), ('AF', 'Africa'), ('AU', 'Australia'), ('LA', 'Latine_America'), ('MA', 'Martial_Arts'), ('FB', 'Football'), ('CR', 'Cricket'), ('F1', 'Formula_1'), ('TE', 'Tennis'), ('GO', 'Golf'), ('AT', 'Athletics'), ('CY', 'Cycling'), ('TECH', 'Technology'), ('S&HE', 'Science_&_Health'), ('BOOK', 'Books'), ('ST', 'Style'), ('TV', 'Film_&_TV'), ('MS', 'Music'), ('AR&D', 'Art_&_Design'), ('EN', 'Entertainment'), ('DE', 'Destinations'), ('FOOD', 'Food_&_Drink'), ('AD', 'Adventures'), ('NW', 'Natural_Wonders'), ('WE&C', 'Weather_&_Climate')], max_length=50, null=True),
        ),
    ]
