# Generated by Django 5.1.3 on 2024-12-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS50_News', '0018_remove_new_scroll_new_featured_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='featured',
            new_name='is_featured',
        ),
        migrations.AddField(
            model_name='new',
            name='is_hero',
            field=models.BooleanField(default=False),
        ),
    ]
