# Generated by Django 5.1.3 on 2024-12-07 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS50_News', '0021_remove_category_news_new_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='category',
        ),
        migrations.AddField(
            model_name='new',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='CS50_News.category'),
        ),
    ]
