# Generated by Django 5.1.3 on 2024-12-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS50_News', '0022_remove_new_category_new_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='category',
        ),
        migrations.RemoveField(
            model_name='new',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='new',
            name='is_hero',
        ),
        migrations.AddField(
            model_name='category',
            name='news',
            field=models.ManyToManyField(blank=True, null=True, related_name='category', to='CS50_News.new'),
        ),
        migrations.AddField(
            model_name='new',
            name='scroll',
            field=models.IntegerField(default=0),
        ),
    ]
