# Generated by Django 5.1.3 on 2024-12-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS50_News', '0023_remove_new_category_remove_new_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='new',
            name='is_hero',
            field=models.BooleanField(default=False),
        ),
    ]
