# Generated by Django 5.1.3 on 2024-12-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS50_News', '0025_new_is_sub_hero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='new',
            name='is_hero',
        ),
        migrations.RemoveField(
            model_name='new',
            name='is_sub_hero',
        ),
        migrations.AddField(
            model_name='new',
            name='section',
            field=models.CharField(blank=True, choices=[('H', 'hero'), ('S', 'side'), ('T', 'top_stories'), ('F', 'featured')], max_length=50, null=True),
        ),
    ]
