# Generated by Django 5.1.3 on 2025-01-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS50_News', '0026_remove_new_is_featured_remove_new_is_hero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.CharField(blank=True, choices=[('N', 'News'), ('S', 'Sport'), ('B', 'Business'), ('I', 'Innovation'), ('C', 'Culture'), ('T', 'Travel'), ('E', 'Earth')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='section',
            field=models.CharField(blank=True, choices=[('H', 'hero'), ('S', 'side'), ('T', 'top_stories'), ('F', 'featured'), ('O', 'only')], max_length=50, null=True),
        ),
    ]
