# Generated by Django 5.1.3 on 2025-03-18 13:11

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS50_News', '0026_remove_new_is_featured_remove_new_is_hero_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(default='', unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='new',
            name='scroll',
        ),
        migrations.RemoveField(
            model_name='new',
            name='section',
        ),
        migrations.AddField(
            model_name='new',
            name='category',
            field=models.CharField(blank=True, choices=[('N', 'News'), ('S', 'Sport'), ('B', 'Business'), ('I', 'Innovation'), ('C', 'Culture'), ('T', 'Travel'), ('E', 'Earth')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='new',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('N', [('IG', 'Israil-Gaza_war'), ('UR', 'Ukraine-Russia_war'), ('IQ', 'Iraq'), ('US&C', 'US_&_Canada'), ('MD', 'Middle_East'), ('EU', 'Europe'), ('AS', 'Asia'), ('AF', 'Africa'), ('AU', 'Australia'), ('LA', 'Latine_America')]), ('S', [('MA', 'Martial_Arts'), ('FB', 'Football'), ('CR', 'Cricket'), ('F1', 'Formula_1'), ('TE', 'Tennis'), ('GO', 'Golf'), ('AT', 'Athletics'), ('CY', 'Cycling')]), ('B', [('B', 'Business')]), ('I', [('TECH', 'Technology'), ('S&HE', 'Science_&_Health')]), ('C', [('BOOK', 'Books'), ('ST', 'Style'), ('TV', 'Film_&_TV'), ('MS', 'Music'), ('AR&D', 'Art_&_Design'), ('EN', 'Entertainment')]), ('T', [('DE', 'Destinations'), ('FOOD', 'Food_&_Drink'), ('AD', 'Adventures')]), ('E', [('NW', 'Natural_Wonders'), ('WE&C', 'Weather_&_Climate')])], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='new',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='user',
            name='saved_articles',
            field=models.ManyToManyField(to='CS50_News.new'),
        ),
        migrations.AlterField(
            model_name='new',
            name='headline',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(upload_to='CS50_News/static/CS50_News/cover'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('H', 'hero'), ('C', 'carousel'), ('F', 'featured'), ('L', 'left'), ('N', 'news'), ('O', 'only'), ('R', 'right'), ('S', 'scroll'), ('M', 'more'), ('T', 'trending')], max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='CS50_News.page')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='CS50_News.new')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='CS50_News.section')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.DeleteModel(
            name='category',
        ),
    ]
