# Generated by Django 5.1.3 on 2025-01-05 13:34

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CS50_News', '0027_alter_category_category_alter_category_parent_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='Israil-Gaza_war, Ukraine-Russia_war, Iraq, US_&_Canada, Middle_East, Europe, Asia, Africa, Australia, Latine_America', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
