# Generated by Django 5.1.3 on 2025-04-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS50_News', '0027_page_remove_new_scroll_remove_new_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='validation_date',
        ),
        migrations.AlterField(
            model_name='section',
            name='position',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
