# Generated by Django 5.1.3 on 2025-04-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS50_News', '0028_remove_user_otp_date_remove_user_validation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='position',
            field=models.PositiveIntegerField(),
        ),
    ]
