# Generated by Django 5.1.3 on 2025-01-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS50_News', '0028_new_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('N', 'News'), ('S', 'Sport'), ('B', 'Business'), ('I', 'Innovation'), ('C', 'Culture'), ('T', 'Travel'), ('E', 'Earth')], max_length=50),
        ),
    ]
