# Generated by Django 5.1.3 on 2025-04-13 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CS50_News', '0029_alter_section_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='score',
        ),
    ]
