# Generated by Django 5.1.3 on 2025-01-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS50_News', '0029_remove_category_parent_alter_category_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='news',
        ),
        migrations.AddField(
            model_name='new',
            name='category',
            field=models.CharField(choices=[('N', 'News'), ('S', 'Sport'), ('B', 'Business'), ('I', 'Innovation'), ('C', 'Culture'), ('T', 'Travel'), ('E', 'Earth')], default='N', max_length=50),
            preserve_default=False,
        ),
    ]
