# Generated by Django 5.1.3 on 2025-01-05 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CS50_News', '0030_remove_category_category_remove_category_news_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
    ]
