# Generated by Django 5.2 on 2025-04-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS50_News', '0030_remove_new_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('N', [('IG', 'Israil-Gaza_war'), ('UR', 'Ukraine-Russia_war'), ('IQ', 'Iraq'), ('US&C', 'US_&_Canada'), ('MD', 'Middle_East'), ('EU', 'Europe'), ('AS', 'Asia'), ('AF', 'Africa'), ('AU', 'Australia'), ('LA', 'Latine_America'), ('WO', 'World'), ('PO', 'Politics')]), ('S', [('MA', 'Martial_Arts'), ('FB', 'Football'), ('CR', 'Cricket'), ('F1', 'Formula_1'), ('TE', 'Tennis'), ('GO', 'Golf'), ('AT', 'Athletics'), ('CY', 'Cycling')]), ('B', [('B', 'Business')]), ('I', [('TECH', 'Technology'), ('S&HE', 'Science_&_Health')]), ('C', [('BOOK', 'Books'), ('ST', 'Style'), ('TV', 'Film_&_TV'), ('MS', 'Music'), ('AR&D', 'Art_&_Design'), ('EN', 'Entertainment')]), ('T', [('DE', 'Destinations'), ('FOOD', 'Food_&_Drink'), ('AD', 'Adventures')]), ('E', [('NW', 'Natural_Wonders'), ('WE&C', 'Weather_&_Climate')])], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='saved_articles',
            field=models.ManyToManyField(blank=True, null=True, to='CS50_News.new'),
        ),
    ]
