# Generated by Django 5.1.3 on 2025-01-06 05:14

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CS50_News', '0031_delete_category'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
