# Generated by Django 5.2 on 2025-06-01 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS50_News', '0031_alter_new_sub_category_alter_user_saved_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='CS50_News.page'),
        ),
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(default='images/test-img.png', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='new',
            name='sub_category',
            field=models.CharField(blank=True, choices=[('N', [('IG', 'Israil-Gaza_war'), ('UR', 'Ukraine-Russia_war'), ('US&C', 'US_&_Canada'), ('MD', 'Middle_East'), ('EU', 'Europe'), ('AS', 'Asia'), ('AF', 'Africa'), ('AU', 'Australia'), ('LA', 'Latine_America'), ('WO', 'World'), ('PO', 'Politics')]), ('S', [('MA', 'Martial_Arts'), ('FB', 'Football'), ('CR', 'Cricket'), ('F1', 'Formula_1'), ('TE', 'Tennis'), ('GO', 'Golf'), ('AT', 'Athletics'), ('CY', 'Cycling'), ('DA', 'Darts'), ('BB', 'Basketball'), ('RU', 'Rugby')]), ('B', [('B', 'Business')]), ('I', [('TECH', 'Technology'), ('S&HE', 'Science_&_Health')]), ('C', [('CU', 'Culture'), ('SO', 'Stories'), ('BOOK', 'Books'), ('ST', 'Style'), ('TV', 'Film_&_TV'), ('MS', 'Music'), ('AR&D', 'Art_&_Design'), ('EN', 'Entertainment')]), ('T', [('DE', 'Destinations'), ('FOOD', 'Food_&_Drink'), ('AD', 'Adventures')]), ('E', [('NW', 'Natural_Wonders'), ('CL', 'Climate'), ('FU', 'Future')])], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='saved_articles',
            field=models.ManyToManyField(to='CS50_News.new'),
        ),
    ]
