# Generated by Django 5.1.3 on 2025-01-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS50_News', '0032_alter_new_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='sub_category',
            field=models.CharField(choices=[('N', [('IG', 'Israil-Gaza_war'), ('UR', 'Ukraine-Russia_war'), ('IQ', 'Iraq'), ('US&C', 'US_&_Canada'), ('MD', 'Middle_East'), ('EU', 'Europe'), ('AS', 'Asia'), ('AF', 'Africa'), ('AU', 'Australia'), ('LA', 'Latine_America')]), ('S', [('MA', 'Martial_Arts'), ('FB', 'Football'), ('CR', 'Cricket'), ('F1', 'Formula_1'), ('TE', 'Tennis'), ('GO', 'Golf'), ('AT', 'Athletics'), ('CY', 'Cycling')]), ('B', None), ('I', [('TECH', 'Technology'), ('S&HE', 'Science_&_Health')]), ('C', [('BOOK', 'Books'), ('ST', 'Style'), ('TV', 'Film_&_TV'), ('MS', 'Music'), ('AR&D', 'Art_&_Design'), ('EN', 'Entertainment')]), ('T', [('DE', 'Destinations'), ('FOOD', 'Food_&_Drink'), ('AD', 'Adventures')]), ('E', [('NW', 'Natural_Wonders'), ('WE&C', 'Weather_&_Climate')])], default='IG', max_length=50),
            preserve_default=False,
        ),
    ]
