# Generated by Django 5.2 on 2025-06-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS50_News', '0032_page_parent_alter_new_image_alter_new_sub_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='page',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
