# Generated by Django 5.1.3 on 2025-02-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS50_News', '0035_alter_new_image_alter_new_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
