# Generated by Django 5.1.3 on 2025-02-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CS50_News', '0037_alter_new_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_articles',
            field=models.ManyToManyField(to='CS50_News.new'),
        ),
        migrations.AlterField(
            model_name='new',
            name='headline',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='new',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
        ),
    ]
